#!/bin/bash

for ((;;)); do
  DIR=/home/stream/capture/cap_gen1_$(date +%Y%m%d_%H%M)/

  mkdir -p $DIR
  cd $DIR

  /home/stream/capture/bmdcapture -C 0 -m 7 -A 2 -V 4 -F nut \
    -o strict=experimental:syncpoints=none -f pipe:1 | \
  ffmpeg -vsync passthrough -y -probesize 200M -i - -force_key_frames 'expr:gte(t,n_forced*30)' \
    -vcodec hevc_nvenc -preset medium \
    -profile:v main -level 4.1 -rc vbr -b:v 10M -rc-lookahead 60 \
    -acodec aac \
    -f segment -segment_time 30 -segment_list cap.ffcat \
    cap%04d.nut
#    -f libndi_newtek -y stream

  # for h264 add -pix_fmt yuv420p
  # for ndi add -pix_fmt rgb0

  echo "Restarting in 5"
  sleep 5
done

