#!/bin/bash

umask 002

for ((;;)); do
  DIR=/home/stream/capture/cap_gen1_$(date +%Y%m%d_%H%M)/

  mkdir -p $DIR
  cd $DIR

  #Input:
  # ffmpeg -copyts -f alsa -i hw:3 -ts abs -f v4l2 -video_size 1920x1080 -i /dev/video2 \
  # ffmpeg -f libndi_newtek -probesize 200M -i "$1" -pix_fmt yuv444p \
  # ffmpeg -f decklink  -i 'DeckLink Mini Recorder 4K' \

  #Codec:
  #  -vcodec hevc_nvenc -preset medium \
  #  -profile:v main -level 4.1 -rc vbr -b:v 15M -rc-lookahead 60 \
  #
  #  -global_quality 18 -rc_mode QVBR \
  #  -vaapi_device /dev/dri/renderD128 \
  #  -vf 'format=nv12,hwupload' -vcodec hevc_vaapi \
  #  -profile:v main -level 4.1 -b:v 15M -maxrate 30M  \

  #  -f segment -segment_time 30 -segment_list cap.ffcat cap%04d.nut

  ffmpeg -f decklink  -i 'DeckLink Mini Recorder 4K' \
    -force_key_frames 'expr:gte(t,n_forced*30)' \
    -global_quality 20 -rc_mode QVBR \
    -vaapi_device /dev/dri/renderD128 \
    -vf 'format=nv12,hwupload' -vcodec hevc_vaapi \
    -profile:v main -level 4.1 -b:v 15M -maxrate 30M  \
    -acodec aac -b:a 196k \
    -f tee -map 0:v -map 0:a "[f=segment:segment_time=30:segment_list=cap.ffcat]cap%04d.nut|[f=mpegts]srt://stream.aketzu.net:8890?streamid=publish:s1&pkt_size=1316"

  echo "Restarting in 5"
  sleep 5
done
